### ISSUE TITLE
RequestLoadSimulator.java = sell your keyboard

### ISSUE THREAD

**Issue by Ben-Mark** [johnrjenson/JavaVsNode#2]
Youre a complete newb talking crap about java.
 you executed threads in parallel where you synchronized the entire cluster,
People like you should stay in their javascript bug world and never enter our realm

Best regards,
A programmer.

**Comment by johnrjenson** [comment]
@Ben-Mark Thank you for taking the time to take a look at the code I wrote. I admire your passion for this topic. I provided justification for my implementation choices in the two blog posts that I wrote explaining the comparison between Java and Node.

https://www.tandemseven.com/blog/node-a-compelling-choice-for-java-developers/
https://www.tandemseven.com/blog/performance-java-vs-node/

One of your observations you made is incorrect: `you executed threads in parallel where you synchronized the entire cluster`. 

While some parts of the code that deal with the performance tracking of the threads, are synchronized, the threads execute their individual work loads in parallel, as you can plainly see by running the simulation, or by simply looking at the code on line 46 of RequestLoadSimulator.java. https://github.com/johnrjenson/JavaVsNode/blob/master/src/main/java/RequestLoadSimulator.java#L46

It is not possible to ascertain the details of a software developer's career by looking at a few lines of code, so it would be foolish to make judgements with such a limited amount of information.

Have a great day.
